name: Deploy PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: compsys.tex
          args: -shell-escape -interaction=nonstopmode
          latexmk_use_xelatex: false
          latexmk_shell_escape: true
          # This ensures multiple compilation passes for TOC generation
          compile_method: latexmk

      - name: Copy
        run: |
          mkdir out
          cp ./compsys.pdf ./out/compsys.pdf
          cp ./index.html ./out/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: compsys-pdf
          path: out/compsys.pdf

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: elazdi-al
          GIT_CONFIG_EMAIL: alielazdi@gmail.com
